### ISSUE TITLE
Train schedules

### ISSUE THREAD

**Issue by solid38** [lgmorand/MMM-Transilien#6] opened 2019-09-02 09:59 UTC
Hi,

The list of upcoming trains is not good.
Indeed, this list takes into account trains that are gone.
It would be necessary to test the estimated time of the train and only take the trains that have a departure time higher than the present time.

Thanks !

**Comment by lgmorand** [comment] 2019-09-02 10:09
Is this something new this issue ?  @deionalims made a PR few days ago.

I don't have MM² anymore so that's hard for me to pinpoint the issue

**Comment by deionalims** [comment] 2019-09-02 10:12
Hello.

What do you mean by `the list of upcoming trains is not good` ? 
When you display the remaining time, trains that are gone are ignored.
It's not the case for regular time. Is it what you mean ?

**Comment by lgmorand** [comment] 2019-09-02 10:13
> Indeed, this list takes into account trains that are gone.

that's weird @solid38, because the list of the train is decided on server side by SNCF API so they should not appear anymore. the module code just format the returned trains

**Comment by solid38** [comment] 2019-09-02 10:20
See screenshot. 

![2019_09_02_12_17_43_Window](https://user-images.githubusercontent.com/54800337/64107992-0250cf80-cd7c-11e9-9b47-3da132d9bede.png)

**Comment by solid38** [comment] 2019-09-02 10:40
I use a similar script in Jeedom, and it seems that the file returned following the call of the API contains already departed trains ...

**Comment by deionalims** [comment] 2019-09-02 10:44
It's the API then.
Normally past trains would stay in the response payload for 1 or 2 minutes after departure. 
I'll check the response payload in detail tonight.

**Comment by solid38** [comment] 2019-09-02 13:42
> 
> 
> It's the API then.
> Normally past trains would stay in the response payload for 1 or 2 minutes after departure.
> I'll check the response payload in detail tonight.

Thanks ;)

**Comment by lgmorand** [comment] 2019-09-02 15:45
Thanks guys, I'm closing it. I do hope they will fix it on server-side

thx FX of your supraspeed reactivity ;)

**Closed as completed by lgmorand** 2019-09-02 15:45 UTC
Labels: wontfix

**Comment by deionalims** [comment] 2019-09-02 18:47
After checking the response payload in details I can confirm that past trains for more than 30mn were still present. 
Those trains ought to be ignored on the display. This also creates a small issue regarding the number of trains to display. As long as it was only one train to ignore it was fine but here we're talking about up to 5 trains. I'll probably take some time in the next days to figure out a fix.

Concerning the Transilien API, it's an old API and I'm pretty sure it's not maintained anymore so no surprise we run into those kind of issue. I allowed myself to send an email to ask them with few to no hope of any answer.

**Comment by lgmorand** [comment] 2019-09-02 19:38
API must be maintained, that's a legal obligation.
I just checked, the api has been updated for the last 4 years. I'm guessing they do some server change and the server is now on the wrong timezone, which cause to display all trains over the last hour.

**Comment by solid38** [comment] 2019-09-14 17:34
Problem is fixed.

**Comment by deionalims** [comment] 2019-09-16 08:42
I actually received an answer from the Transilien API team and they confirmed that they fixed the issue. 
I still plan to improve the module to ignore the past trains while keeping the configured number of trains to display.
